### ISSUE TITLE
Hollisitic Pose with ReadyPlayer Me Avatar

### ISSUE THREAD

**Issue by JpEncausse** [yeemachine/kalidokit#67]
Hello,
Thanks for your component that fill the gap between MediaPipe and Avatar Puppetering.

I made a small JSFiddle using ReadyPlayer Me Avatar with MediaPipe and Kalidokit
https://jsfiddle.net/c0gxfk9y/1/

I only setup the `Kalidokit.Pose.solve()` I don't know if I correctly apply the pose Rig ? The animations seems OK but the arms are upside down. 

I didn't apply the position/rotation on hips, because the avatar is moved anywhere. Next I'll add hand pose.

Can you point me in the right direction ? I feel close to something that would correctly do the job.

**Comment by JpEncausse** [comment]
Another try inspired from /script code using the quaternion rotation
https://jsfiddle.net/nxg5bp2h/1/

**Comment by yeemachine** [comment]
Yea, different 3D models rigged differently will perform differently because the initial joint rotation (how it's loaded into three.js) is different. The solve is essentially to retarget the joint rotations by a per joint basis (flip the direction, swap the axis etc)

**Comment by JpEncausse** [comment]
Damned, that's what I thought :-/ do I have to rotate afterLoad the joins or after call to rotate  function ?
Mmm I sucks so much at 3D i'll dig :-P (don't understand why guys at ReadyPlayer Me didnt' do something standard on that

**Comment by yeemachine** [comment]
I've been working on the Mediapipe team to deprecate KalidoKit. In the future, Mediapipe's models will output these values for avatar puppeteering directly.

We already released a promo video and demoed it at CVPR last summer. In that demo, we made conversions for VRM, Mixamo, and ReadyPlayerMe models. I'm not sure when this will eventually release for the public, but everything has been trained and showcased.

**Comment by JpEncausse** [comment]
So cool, any link to the demo/video ? May be you could share the ReadyPlayerMe conversion (I also asked on MediaPipe repo) ?
With 3 models compatible so much thing to do after  :-)

**Comment by Colorfingers** [comment]
> I've been working on the Mediapipe team to deprecate KalidoKit. In the future, Mediapipe's models will output these values for avatar puppeteering directly.
> 
> We already released a promo video and demoed it at CVPR last summer. In that demo, we made conversions for VRM, Mixamo, and ReadyPlayerMe models. I'm not sure when this will eventually release for the public, but everything has been trained and showcased.

Enthusiastically looking forward to this... I've spent most of my Christmas break trying to get the kalidoKit.js to cooperate with a Mixamo model...  It would be super great if there was already a trained model for this...  Please post here when it is so we can easily find it.  Thank you for all you do!

**Comment by Colorfingers** [comment]
> Damned, that's what I thought :-/ do I have to rotate afterLoad the joins or after call to rotate function ? Mmm I sucks so much at 3D i'll dig :-P (don't understand why guys at ReadyPlayer Me didnt' do something standard on that
> 
> EDIT: I did some test playing with one arm and switch/reverse axis but no success. it seems to be more tricky :-/
> 
> ```
>    this.rigRotation('RightUpperArm', {
>         x: riggedPose.LeftUpperArm.z,
>         y: riggedPose.LeftUpperArm.y,
>         z: -riggedPose.LeftUpperArm.x,
>     },1, 0.3)
> ```
> 
> If you can add a compatible version for ReadyPlayer Me **it would be so so so awesome** 🙏 since ReadyPlayer Me is becoming popular to build an avatar with lipsync, mixamo, etc ... ([I read L'Oreal invest into ReadyPlayerMe](https://www.forbes.com/sites/stephaniehirschmiller/2022/11/17/loreal-creates-digital-beauty-looks-for-ready-player-me-avators/)) I don't know other "Avatar Creator" so easy to provide a GLB.
> 
> [Mesekai (another project)](https://github.com/Neleac/Mesekai/blob/readyplayerme/scripts/avatar.js) did some test but stop with only left hand and switch to Unity. And I have hard time to understand the 3D code.

I have had some better results changing the value of rotation.y ... I've tried a number of things and this worked best ...

`let euler = new this.THREE.Euler(rotation.x * dampener, rotation.z * dampener, -rotation.y * dampener)
let quaternion = new this.THREE.Quaternion().setFromEuler(euler).inverse();`

I will share if I find a better solution... this still does not do a great job with hand animations...

**Comment by Colorfingers** [comment]
> Yea, different 3D models rigged differently will perform differently because the initial joint rotation (how it's loaded into three.js) is different. The solve is essentially to retarget the joint rotations by a per joint basis (flip the direction, swap the axis etc)

I think I know what you mean... can you provide a small example just to make sure? this sounds like a cat herding expedition.. Are we changing the values supplied in kilidokit.js?

**Comment by JpEncausse** [comment]
Got the same headheck :-)
1. For : RightUpperArm / LeftUpperArm / RightLowerArm / LeftLowerArm I find the less worst solution is x, z, -y
But raising arm in front of you is still strange ...

```
 this.rigRotation('RightLowerArm', {
     x :  riggedPose.RightLowerArm.x,
     y :  riggedPose.RightLowerArm.z,
     z :  -riggedPose.RightLowerArm.y,
}, 1, 0.4)
```

2. For hips I do something the opposite to keep the mirror effect
```
    this.rigPosition('Hips', {
        x: -riggedPose.Hips.position.x,
        y: riggedPose.Hips.position.y + 1, 
        z: -riggedPose.Hips.position.z 
    }, 1, 0.3)
```

For Chest and Spine I do like 1. but it's not very accurate compared to the result drawing with MediaPipe.
I think 
- Kalidokit do some adjustement that can break things
- There is something to do with elbow for better rotation of upper arm
- Same for lower leg that are some how strange when you raise them on the side they go the opposit

I keep digging, ... but I would love a real official solution since it is so important to have multiple avatar libraries working with MediaPipe. Yes MediaPipe is very cool but half-useless if only drawing works not avataring.

**Comment by yeemachine** [comment]
This is the [demo](https://twitter.com/yeemachine/status/1539639359657447424?s=46&t=wcQWkr_HpkgAmNOQgIZd8w) we shared at CVPR last summer. 

We demoed it with VRM, ReadyPlayerMe, and Mixamo avatars. Unfortunately, this is all I can share. I will be pushing for the public release of the new model.

**Comment by Colorfingers** [comment]
> 
With a great deal of fiddling... this seems to work the best for me:
`
     x = -rotation.x; // Reverse direction
     y = rotation.z; 
     z = -rotation.y; // Reverse direction    
`
I examined my rig and compared it to the VRM rig and I found the spin, head, hips and eyes were on the same orientation.  The arms and fingers are opposite from each other on the left and right side and differ in orientation than the VRM... that will take some time to figure out... The above worked for both arms... not sure why but I won't complain.... hope the fingers will work as well... we will see...
